# Generated by Django 4.2.7 on 2026-01-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_app', '0003_remove_payment_payment_id_payment_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='wifisession',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='wifisession',
            name='start_time',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
