# Generated by Django 4.2.7 on 2026-01-18 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_app', '0004_remove_payment_transaction_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='mac',
            field=models.CharField(default='UNKNOWN', max_length=30),
        ),
        migrations.AddField(
            model_name='wifisession',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='wifisession',
            name='mac_address',
            field=models.CharField(max_length=30),
        ),
    ]
