# Generated by Django 4.2.7 on 2026-01-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_app', '0005_remove_payment_payment_id_payment_mac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='mac',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='wifisession',
            name='mac_address',
            field=models.CharField(max_length=50),
        ),
    ]
