# Generated by Django 4.2.7 on 2026-01-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_app', '0006_alter_payment_mac_alter_wifisession_mac_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='commune',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='router_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wifisession',
            name='commune',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wifisession',
            name='router_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mac',
            field=models.CharField(max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success')], max_length=10),
        ),
        migrations.AlterField(
            model_name='wifisession',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wifisession',
            name='mac_address',
            field=models.CharField(max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name='wifisession',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
